### ISSUE TITLE
Custom functions not working when excluded from "compile" item group in VS

### ISSUE THREAD

**Issue by satfx** [NeVeSpl/NTypewriter#48]
I'm trying to use custom functions in my project, but unable to make them work without including its .cs in the "compile" item group. I.e. it is not working when I do the following:

```
<ItemGroup>
	<Compile Remove="CustomFunctions.nt.cs" />
	<None Include="CustomFunctions.nt.cs" />
</ItemGroup>
```

The main reason to make that is to exclude NTypewriter custom code from my main code, since I consider it as service code, i.e. dev only. And in the NTypewriter docs there were said that it compiles custom functions code outside the project and its settings it was declared.

Is it a bug or what I'm doing wrong? Thank you in advance!

NTypewriter v0.3.0

**Comment by NeVeSpl** [comment]
Yes, there are compiled outside of the project that includes them. The problem is that Roslyn API is used to find configuration files, and Roslyn API only sees files that have build action set on "compile". The problematic code is here [GetDecoratedSyntaxTreesWithAttribute](https://github.com/NeVeSpl/NTypewriter/blob/d1a39c1c2c342e9b44b803f5995e9b8f64f6ee83/NTypewriter.Runtime/UserCode/UserCodeLoader.cs#L122).

Right now there is a no way of achieving what you want, but it may appear in future versions.
