### ISSUE TITLE
execute NTypewriter as a dotnet tool

### ISSUE THREAD

**Issue by harishrathi** [NeVeSpl/NTypewriter#49]
I am not sure if its possible, if it is - that would help a lot in CI/CD automation. 
Also, I can run it as a vscode command rather than depending on visual studio.

**Comment by NeVeSpl** [comment]
NTypewriter does not have any dependency on VS. You can build your own [CLI](https://github.com/NeVeSpl/NTypewriter/blob/master/Documentation/CLI.md) or use one of existing [
NTypewriterCLI ](https://github.com/TietoEVRY/NTypewriterCLI). Since CLI is possible you can integrate NTypewriter with whateever you want.
