### ISSUE TITLE
Can the Visual Studio extension auto-update TS files upon changing a C# class?

### ISSUE THREAD

**Issue by washamdev** [NeVeSpl/NTypewriter#71]
We are converting our solution from using Typewriter's Visual Studio extension to using NTypewriter's. One thing I'm seeing that's different is that Typewriter automatically adds/updates TS files when you make a change to a C# file that is configured to render to TS, but NTypewriter seems to require us to find an .nt file in the Solution Explorer, right-click it, and click to "Render" or "Render All", which is more clicks for every change. Is there a way to automate this like Typewriter does where a chance on a C# class automatically updates the corresponding TS file?

**Comment by gregveres** [comment]
I have my setup configured to build the ts files on build. It is a configuration setting in NTypewritter. I find it works much better that typewriter because I used to have typewriter hang visual studio every time I saved. With this set I don’t have that problem at all. On Mar 15, 2023, at 5:48 PM, John ***@***.***> wrote:﻿
We are converting our solution from using Typewriter's Visual Studio extension to using NTypewriter's. One thing I'm seeing that's different is that Typewriter automatically adds/updates TS files when you make a change to a C# file that is configured to render to TS, but NTypewriter seems to require us to find an .nt file in the Solution Explorer, right-click it, and click to "Render" or "Render All", which is more clicks for every change. Is there a way to automate this like Typewriter does where a chance on a C# class automatically updates the corresponding TS file?
