### ISSUE TITLE
Is NTypewriter.SourceGenerator intended to add rendered templates to compilation source?

### ISSUE THREAD

**Issue by amdavie** [NeVeSpl/NTypewriter#74]
Hello @NeVeSpl 

I just got around to looking at your SourceGenerator project from the last release as this is something I would be very interested in because I mainly write C# templates.

I realize this was the initial release, but looking at the source code for the SourceGenerator it does not actually add any rendered nt templates to the compilation source (i.e. `AddSource`) but only renders them to file. Is this intentional? And if so, what is the purpose of using a C# source generator? Is adding to the compilation source something you are open to the project supporting? I suppose there would need to be a way to distinguish between an nt template that renders C# and ones that do not.

I'm just trying to understand the intention of this project since it is in fact using a C# source generator at its core.

Thanks.

**Comment by gregveres** [comment]
@amdavie I am not going to try to answer for @NeVeSpl, but I will say that there are very valid use cases for generating the TS files and not having them inserted into the project.

My project generates approximately 700 TS files (enums, interfaces and service entry points). I used to use Typewriter for this, which always inserts the files into the project and it would take forever, introducing 10-20 second lockups. 
When I migrated to NTypewriter, I changed things up so that these files get generated into the stand alone front end directory and not into a project directory. With this setup, NTypewriter is sub 1 second and everything works great. 

I just wanted to point out that there are valid reasons for not adding the files to a project.

**Comment by NeVeSpl** [comment]
As @gregveres already mentioned the main job of NTypewriter is to generate TypeScript files. 

SourceGenerator is the youngest addition to NTypewriter family, offering the bare minimum functionality. 

Detecting C# files through extensions `*.cs` and adding them to compilation was planned from the beginning, but since generating C# is not a base scenario, it did not make it to the first release of SG. I would not mind if any PR appeared and added that functionality.

**Comment by NeVeSpl** [comment]
For now, I do not think that anything more explicit is necessary, just a simple check of generated file extension would be enough.
